-- FIXME Scalar DB SQL doesn't support multiple statement execution
-- create namespace if not exists "scldb_ns";
-- create table if not exists `scldb_ns.group` (id bigint, name text, primary key (id));
-- create table if not exists `scldb_ns.user` (id bigint, name text, group_id bigint, point int, primary key (id));
